// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Box$ReactHooksTemplate = require("./Box.bs.js");

function Component1(Props) {
  return React.createElement("div", undefined, "message", React.createElement(Box$ReactHooksTemplate.make, {
                  children: "message",
                  p: /* `sc */[
                    25744,
                    2
                  ],
                  mt: /* `sc */[
                    25744,
                    1
                  ]
                }));
}

var make = Component1;

exports.make = make;
/* react Not a pure module */
